### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet
  id: EntitySet
  parent: NDSH.Geospatial.MetadataDB.Relational.Configurations
  children:
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet.MdMetadataConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet.MetadataXmlDocumentConfiguration
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.ISO19115.Ed2003.DB
references:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet.MdMetadataConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet.MdMetadataConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet.MdMetadataConfiguration.html
  name: MdMetadataConfiguration
  nameWithType: MdMetadataConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet.MdMetadataConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet.MetadataXmlDocumentConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet.MetadataXmlDocumentConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet.MetadataXmlDocumentConfiguration.html
  name: MetadataXmlDocumentConfiguration
  nameWithType: MetadataXmlDocumentConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.EntitySet.MetadataXmlDocumentConfiguration
