### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema
  id: ConceptualSchema
  parent: NDSH.Geospatial.MetadataDB.Relational.Configurations
  children:
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.Text
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema
  type: Namespace
references:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
  href: NDSH.html
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
  spec.csharp:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB
    name: MetadataDB
    href: NDSH.Geospatial.MetadataDB.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational
    name: Relational
    href: NDSH.Geospatial.MetadataDB.Relational.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations
    name: Configurations
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema
    name: ConceptualSchema
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived
    name: Derived
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
    name: UnitsOfMeasure
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure.html
  spec.vb:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB
    name: MetadataDB
    href: NDSH.Geospatial.MetadataDB.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational
    name: Relational
    href: NDSH.Geospatial.MetadataDB.Relational.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations
    name: Configurations
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema
    name: ConceptualSchema
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived
    name: Derived
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
    name: UnitsOfMeasure
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure.html
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
  href: NDSH.html
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
  spec.csharp:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB
    name: MetadataDB
    href: NDSH.Geospatial.MetadataDB.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational
    name: Relational
    href: NDSH.Geospatial.MetadataDB.Relational.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations
    name: Configurations
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema
    name: ConceptualSchema
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation
    name: Implementation
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
    name: Names
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.html
  spec.vb:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB
    name: MetadataDB
    href: NDSH.Geospatial.MetadataDB.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational
    name: Relational
    href: NDSH.Geospatial.MetadataDB.Relational.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations
    name: Configurations
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema
    name: ConceptualSchema
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation
    name: Implementation
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
    name: Names
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.html
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.Text
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.Text
  href: NDSH.html
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.Text
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.Text
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.Text
  spec.csharp:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB
    name: MetadataDB
    href: NDSH.Geospatial.MetadataDB.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational
    name: Relational
    href: NDSH.Geospatial.MetadataDB.Relational.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations
    name: Configurations
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema
    name: ConceptualSchema
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive
    name: Primitive
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.Text
    name: Text
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.Text.html
  spec.vb:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB
    name: MetadataDB
    href: NDSH.Geospatial.MetadataDB.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational
    name: Relational
    href: NDSH.Geospatial.MetadataDB.Relational.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations
    name: Configurations
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema
    name: ConceptualSchema
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive
    name: Primitive
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.Text
    name: Text
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Primitive.Text.html
