### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance
  id: Maintenance
  parent: NDSH.Geospatial.MetadataDB.Relational.Configurations
  children:
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.AttributeInstancesScopeDescriptionConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.AttributesScopeDescriptionConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.DatasetScopeDescriptionConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.FeatureInstancesScopeDescriptionConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.FeaturesScopeDescriptionConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.MdMaintenanceInformationConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.MdScopeDescriptionConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.OtherScopeDescriptionConfiguration
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.ISO19115.Ed2003.DB
references:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.AttributeInstancesScopeDescriptionConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.AttributeInstancesScopeDescriptionConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.AttributeInstancesScopeDescriptionConfiguration.html
  name: AttributeInstancesScopeDescriptionConfiguration
  nameWithType: AttributeInstancesScopeDescriptionConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.AttributeInstancesScopeDescriptionConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.AttributesScopeDescriptionConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.AttributesScopeDescriptionConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.AttributesScopeDescriptionConfiguration.html
  name: AttributesScopeDescriptionConfiguration
  nameWithType: AttributesScopeDescriptionConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.AttributesScopeDescriptionConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.DatasetScopeDescriptionConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.DatasetScopeDescriptionConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.DatasetScopeDescriptionConfiguration.html
  name: DatasetScopeDescriptionConfiguration
  nameWithType: DatasetScopeDescriptionConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.DatasetScopeDescriptionConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.FeatureInstancesScopeDescriptionConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.FeatureInstancesScopeDescriptionConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.FeatureInstancesScopeDescriptionConfiguration.html
  name: FeatureInstancesScopeDescriptionConfiguration
  nameWithType: FeatureInstancesScopeDescriptionConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.FeatureInstancesScopeDescriptionConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.FeaturesScopeDescriptionConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.FeaturesScopeDescriptionConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.FeaturesScopeDescriptionConfiguration.html
  name: FeaturesScopeDescriptionConfiguration
  nameWithType: FeaturesScopeDescriptionConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.FeaturesScopeDescriptionConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.MdMaintenanceInformationConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.MdMaintenanceInformationConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.MdMaintenanceInformationConfiguration.html
  name: MdMaintenanceInformationConfiguration
  nameWithType: MdMaintenanceInformationConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.MdMaintenanceInformationConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.MdScopeDescriptionConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.MdScopeDescriptionConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.MdScopeDescriptionConfiguration.html
  name: MdScopeDescriptionConfiguration
  nameWithType: MdScopeDescriptionConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.MdScopeDescriptionConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.OtherScopeDescriptionConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.OtherScopeDescriptionConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.OtherScopeDescriptionConfiguration.html
  name: OtherScopeDescriptionConfiguration
  nameWithType: OtherScopeDescriptionConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Maintenance.OtherScopeDescriptionConfiguration
