//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSH.Utilities.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDSH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#region Header
        ///// Title Name        : 
        ///// Member of         : 
        ///// Description       : 
        ///// Created by        : @@dd@@/01/2023, @@hh@@:@@mm@@, @@Coder@@.
        ///// Updated by        : 
        ///// Version           : 1.0.0
        ///// GitHub Repository : https://github.com/UoMResearchIT/nerc-digital-solutions-hub
        ///// License           : MIT Licence
        ///// Copyright         : 
        /////
        ///// Comments          : 
        ///#endregion
        ///
        ///#region Imported Namespaces
        ///
        ///using NDSH.Geospatial.Metadata.V19136.Common;
        ///using Newtonsoft.Json;
        ///using Sy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassTemplatePropertyType1 {
            get {
                return ResourceManager.GetString("ClassTemplatePropertyType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#region Header
        ///
        ///// Title Name        : 
        ///// Member of         : 
        ///// Description       : 
        ///// Created by        : @@dd@@/01/2023, @@hh@@:@@mm@@, @@Coder@@.
        ///// Updated by        : 
        ///// Version           : 1.0.0
        ///// GitHub Repository : https://github.com/UoMResearchIT/nerc-digital-solutions-hub
        ///// License           : MIT Licence
        ///// Copyright         : 
        /////
        ///// Comments          : 
        ///#endregion
        ///
        ///#region Imported Namespaces
        ///
        ///using Newtonsoft.Json;
        ///using System;
        ///using System.Collections.Generic;
        ///usi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassTemplatePropertyType2 {
            get {
                return ResourceManager.GetString("ClassTemplatePropertyType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#region Header
        ///// Title Name        : 
        ///// Member of         : 
        ///// Description       : 
        ///// Created by        : @@dd@@/01/2023, @@hh@@:@@mm@@, @@Coder@@.
        ///// Updated by        : 
        ///// Version           : 1.0.0
        ///// GitHub Repository : https://github.com/UoMResearchIT/nerc-digital-solutions-hub
        ///// License           : MIT Licence
        ///// Copyright         : 
        /////
        ///// Comments          : 
        ///#endregion
        ///
        ///#region Imported Namespaces
        ///
        ///using NDSH.Geospatial.Metadata.V19136.Common;
        ///using Newtonsoft.Json;
        ///using Sy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassTemplateType {
            get {
                return ResourceManager.GetString("ClassTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private List&lt;@@Type@@&gt; _@@Element@@;
        ///    
        ///    /// &lt;summary&gt;
        ///    /// 
        ///    /// &lt;/summary&gt;
        ///    [XmlElement(&quot;@@Element@@&quot;, Order = @@Order@@)]
        ///    [JsonProperty(&quot;@@Element@@&quot;, Order = @@Order@@)]
        ///    public List&lt;@@Type@@&gt; @@Property@@ {
        ///      get {
        ///        return _@@Element@@;
        ///      }
        ///      set {
        ///        if (_@@Element@@ == value) {
        ///          return;
        ///        }
        ///        if (_@@Element@@ == null || _@@Element@@.Equals(value) != true) {
        ///          _@@Element@@ = value;
        ///          OnPropertyChanged(); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PropertyListTemplate {
            get {
                return ResourceManager.GetString("PropertyListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private @@Type@@ _@@Element@@;
        ///
        ///    /// &lt;summary&gt;
        ///    /// 
        ///    /// &lt;/summary&gt;
        ///    [XmlElement(&quot;@@Element@@&quot;, Order = @@Order@@)]
        ///    [JsonProperty(&quot;@@Element@@&quot;, Order = @@Order@@)]
        ///    public @@Type@@ @@Property@@ {
        ///      get {
        ///        return _@@Element@@;
        ///      }
        ///      set {
        ///        if (_@@Element@@ == value) {
        ///          return;
        ///        }
        ///        if (_@@Element@@ == null || _@@Element@@.Equals(value) != true) {
        ///          _@@Element@@ = value;
        ///          OnPropertyChanged();
        ///        }
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PropertyObjectTemplate {
            get {
                return ResourceManager.GetString("PropertyObjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:complexType name=&quot;MI_Requirement_Type&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Description: requirement to be satisfied by the planned data acquisition - shortName: Requirement&lt;/xs:documentation&gt;
        ///		&lt;/xs:annotation&gt;
        ///		&lt;xs:complexContent&gt;
        ///			&lt;xs:extension base=&quot;gco:AbstractObject_Type&quot;&gt;
        ///				&lt;xs:sequence&gt;
        ///					&lt;xs:element name=&quot;citation&quot; type=&quot;gmd:CI_Citation_PropertyType&quot; minOccurs=&quot;0&quot;/&gt;
        ///					&lt;xs:element name=&quot;identifier&quot; type=&quot;gmd:MD_Identifier_PropertyType&quot;/&gt;
        ///					&lt;xs:element name=&quot;requestor&quot; t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestXsdString0 {
            get {
                return ResourceManager.GetString("TestXsdString0", resourceCulture);
            }
        }
    }
}
