//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSH.Geospatial.Metadata.ISO19115.Ed2003.Tests.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CitationInformationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CitationInformationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDSH.Geospatial.Metadata.ISO19115.Ed2003.Tests.Content.CitationInformationResourc" +
                            "es", typeof(CitationInformationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_Address_PropertyType {
            get {
                return ResourceManager.GetString("CI_Address_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Address&gt;
        ///  &lt;gmd:deliveryPoint&gt;
        ///    &lt;gco:CharacterString&gt;Environmental Science Centre, Keyworth&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:deliveryPoint&gt;
        ///  &lt;gmd:city&gt;
        ///    &lt;gco:CharacterString&gt;NOTTINGHAM&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:city&gt;
        ///  &lt;gmd:administrativeArea&gt;
        ///    &lt;gco:CharacterString&gt;NOTTINGHAMSHIRE&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:administrativeArea&gt;
        ///  &lt;gmd:postalCode&gt;
        ///    &lt;gco:CharacterString&gt;NG12 5GG&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:postalCode&gt;
        ///  &lt;gmd:country&gt;
        ///    &lt;gco:CharacterString&gt;United King [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CI_Address_Type {
            get {
                return ResourceManager.GetString("CI_Address_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Citation&gt;
        ///  &lt;gmd:title&gt;
        ///    &lt;gco:CharacterString&gt;Geological Indicators of Flooding Great Britain&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:title&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gmd:CI_Date&gt;
        ///      &lt;gmd:date&gt;
        ///        &lt;gco:Date&gt;2006&lt;/gco:Date&gt;
        ///      &lt;/gmd:date&gt;
        ///      &lt;gmd:dateType&gt;
        ///        &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;creation&quot;&gt;creation&lt;/gmd:CI_DateTypeCode&gt;
        ///      &lt;/gmd:dateType&gt;
        ///    &lt;/gmd:CI_Date&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CI_Citation_Type {
            get {
                return ResourceManager.GetString("CI_Citation_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_Contact_PropertyType {
            get {
                return ResourceManager.GetString("CI_Contact_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Contact&gt;
        ///  &lt;gmd:phone&gt;
        ///    &lt;gmd:CI_Telephone&gt;
        ///      &lt;gmd:voice&gt;
        ///        &lt;gco:CharacterString&gt;+44 115 936 3100&lt;/gco:CharacterString&gt;
        ///      &lt;/gmd:voice&gt;
        ///    &lt;/gmd:CI_Telephone&gt;
        ///  &lt;/gmd:phone&gt;
        ///  &lt;gmd:address&gt;
        ///    &lt;gmd:CI_Address&gt;
        ///      &lt;gmd:deliveryPoint&gt;
        ///        &lt;gco:CharacterString&gt;Environmental Science Centre, Keyworth&lt;/gco:CharacterString&gt;
        ///      &lt;/gmd:deliveryPoint&gt;
        ///      &lt;gmd:city&gt;
        ///        &lt;gco:CharacterString&gt;NOTTINGHAM&lt;/gco:CharacterString&gt;
        ///      &lt;/gmd:city&gt;
        ///      &lt;gmd:administra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CI_Contact_Type {
            get {
                return ResourceManager.GetString("CI_Contact_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_Date_PropertyType {
            get {
                return ResourceManager.GetString("CI_Date_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Date&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gco:Date&gt;2006&lt;/gco:Date&gt;
        ///  &lt;/gmd:date&gt;
        ///  &lt;gmd:dateType&gt;
        ///    &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;creation&quot;&gt;creation&lt;/gmd:CI_DateTypeCode&gt;
        ///  &lt;/gmd:dateType&gt;
        ///&lt;/gmd:CI_Date&gt;.
        /// </summary>
        internal static string CI_Date_Type {
            get {
                return ResourceManager.GetString("CI_Date_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;creation&quot;&gt;creation&lt;/gmd:CI_DateTypeCode&gt;.
        /// </summary>
        internal static string CI_DateTypeCode_PropertyType {
            get {
                return ResourceManager.GetString("CI_DateTypeCode_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_Individual_PropertyType {
            get {
                return ResourceManager.GetString("CI_Individual_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_Individual_Type {
            get {
                return ResourceManager.GetString("CI_Individual_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_OnLineFunctionCode_PropertyType {
            get {
                return ResourceManager.GetString("CI_OnLineFunctionCode_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_OnlineResource_PropertyType {
            get {
                return ResourceManager.GetString("CI_OnlineResource_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_OnlineResource_Type {
            get {
                return ResourceManager.GetString("CI_OnlineResource_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_Organisation_Type {
            get {
                return ResourceManager.GetString("CI_Organisation_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_PresentationFormCode_PropertyType {
            get {
                return ResourceManager.GetString("CI_PresentationFormCode_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_Responsibility_PropertyType {
            get {
                return ResourceManager.GetString("CI_Responsibility_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_Responsibility_Type {
            get {
                return ResourceManager.GetString("CI_Responsibility_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_ResponsibleParty&gt;
        ///  &lt;gmd:organisationName&gt;
        ///    &lt;gco:CharacterString&gt;British Geological Survey&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:organisationName&gt;
        ///  &lt;gmd:contactInfo&gt;
        ///    &lt;gmd:CI_Contact&gt;
        ///      &lt;gmd:phone&gt;
        ///        &lt;gmd:CI_Telephone&gt;
        ///          &lt;gmd:voice&gt;
        ///            &lt;gco:CharacterString&gt;+44 115 936 3100&lt;/gco:CharacterString&gt;
        ///          &lt;/gmd:voice&gt;
        ///        &lt;/gmd:CI_Telephone&gt;
        ///      &lt;/gmd:phone&gt;
        ///      &lt;gmd:address&gt;
        ///        &lt;gmd:CI_Address&gt;
        ///          &lt;gmd:deliveryPoint&gt;
        ///            &lt;gco:Char [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CI_ResponsiblePartyType {
            get {
                return ResourceManager.GetString("CI_ResponsiblePartyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_RoleCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_RoleCode&quot; codeListValue=&quot;pointOfContact&quot;&gt;pointOfContact&lt;/gmd:CI_RoleCode&gt;.
        /// </summary>
        internal static string CI_RoleCode_PropertyType {
            get {
                return ResourceManager.GetString("CI_RoleCode_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_Series_PropertyType {
            get {
                return ResourceManager.GetString("CI_Series_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_Series_Type {
            get {
                return ResourceManager.GetString("CI_Series_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_Telephone_PropertyType {
            get {
                return ResourceManager.GetString("CI_Telephone_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Telephone&gt;
        ///  &lt;gmd:voice&gt;
        ///    &lt;gco:CharacterString&gt;+44 115 936 3100&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:voice&gt;
        ///&lt;/gmd:CI_Telephone&gt;.
        /// </summary>
        internal static string CI_Telephone_Type {
            get {
                return ResourceManager.GetString("CI_Telephone_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string CI_TelephoneTypeCode_PropertyType {
            get {
                return ResourceManager.GetString("CI_TelephoneTypeCode_PropertyType", resourceCulture);
            }
        }
    }
}
