//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSH.Geospatial.Metadata.ISO19115.Ed2003.Tests.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetadataInformationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataInformationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDSH.Geospatial.Metadata.ISO19115.Ed2003.Tests.Content.MetadataInformationResourc" +
                            "es", typeof(MetadataInformationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;mdb:MD_Metadata xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        /// xmlns:mdb=&quot;http://standards.iso.org/iso/19115/-3/mdb/2.0&quot;
        /// xmlns:gco=&quot;http://standards.iso.org/iso/19115/-3/gco/1.0&quot;
        /// xmlns:mcc=&quot;http://standards.iso.org/iso/19115/-3/mcc/1.0&quot;
        /// xmlns:mri=&quot;http://standards.iso.org/iso/19115/-3/mri/1.0&quot;
        /// xmlns:lan=&quot;http://standards.iso.org/iso/19115/-3/lan/1.0&quot;
        /// xmlns:cit=&quot;http://standards.iso.org/iso/19115/-3/cit/2.0&quot;
        /// xsi:schemaLocation=&quot;http://standards.is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MD_Metada_XmlDocument_Minimal {
            get {
                return ResourceManager.GetString("MD_Metada_XmlDocument_Minimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:MD_Metadata xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gmx=&quot;http://www.isotc211.org/2005/gmx&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; xmlns:srv=&quot;http://www.isotc211.org/2005/srv&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:geonet=&quot;http://www.fao.org/geonetwork&quot; xsi:schemaLocation=&quot;http://www.isotc211.org/2005/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MD_Metadata_XmlDocument01 {
            get {
                return ResourceManager.GetString("MD_Metadata_XmlDocument01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:MD_Metadata xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gmx=&quot;http://www.isotc211.org/2005/gmx&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:srv=&quot;http://www.isotc211.org/2005/srv&quot; xmlns:geonet=&quot;http://www.fao.org/geonetwork&quot; xsi:schemaLocation=&quot;http://www.isotc211.org/2005/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MD_Metadata_XmlDocument02 {
            get {
                return ResourceManager.GetString("MD_Metadata_XmlDocument02", resourceCulture);
            }
        }
    }
}
