//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSH {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CitationInformationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CitationInformationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDSH.CitationInformationResources", typeof(CitationInformationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gco:CharacterString xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot;&gt;This is a character string&lt;/gco:CharacterString&gt;.
        /// </summary>
        public static string CharacterString {
            get {
                return ResourceManager.GetString("CharacterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gco:CharacterString xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot;&gt;This is a character string&lt;/gco:CharacterString&gt;.
        /// </summary>
        public static string CharacterString_Compact {
            get {
                return ResourceManager.GetString("CharacterString_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:Entity xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gmx=&quot;http://www.isotc211.org/2005/gmx&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; xmlns:srv=&quot;http://www.isotc211.org/2005/srv&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CharacterString_Entity {
            get {
                return ResourceManager.GetString("CharacterString_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:Entity xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gmx=&quot;http://www.isotc211.org/2005/gmx&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; xmlns:srv=&quot;http://www.isotc211.org/2005/srv&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CharacterString_Entity_Compact {
            get {
                return ResourceManager.GetString("CharacterString_Entity_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_Address_PropertyType {
            get {
                return ResourceManager.GetString("CI_Address_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Address xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt;
        ///  &lt;gmd:deliveryPoint&gt;
        ///    &lt;gco:CharacterString xmlns:gmd=&quot;http://www.isotc211.org/2005/gco&quot;&gt;Environmental Science Centre, Keyworth&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:deliveryPoint&gt;
        ///  &lt;gmd:city&gt;
        ///    &lt;gco:CharacterString xmlns:gmd=&quot;http://www.isotc211.org/2005/gco&quot;&gt;NOTTINGHAM&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:city&gt;
        ///  &lt;gmd:administrativeArea&gt;
        ///    &lt;gco:CharacterString xmlns:gmd=&quot;http://www.isotc211.org/2005/gco&quot;&gt;NOTTINGHAMSHIRE&lt;/gco:CharacterString&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CI_Address_Type {
            get {
                return ResourceManager.GetString("CI_Address_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Address xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt;&lt;gmd:deliveryPoint&gt;&lt;gco:CharacterString xmlns:gmd=&quot;http://www.isotc211.org/2005/gco&quot;&gt;Environmental Science Centre, Keyworth&lt;/gco:CharacterString&gt;&lt;/gmd:deliveryPoint&gt;&lt;gmd:city&gt;&lt;gco:CharacterString xmlns:gmd=&quot;http://www.isotc211.org/2005/gco&quot;&gt;NOTTINGHAM&lt;/gco:CharacterString&gt;&lt;/gmd:city&gt;&lt;gmd:administrativeArea&gt;&lt;gco:CharacterString xmlns:gmd=&quot;http://www.isotc211.org/2005/gco&quot;&gt;NOTTINGHAMSHIRE&lt;/gco:CharacterString&gt;&lt;/gmd:administrativeArea&gt;&lt;gmd:postalCode [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CI_Address_Type_Compact {
            get {
                return ResourceManager.GetString("CI_Address_Type_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:Entity xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gmx=&quot;http://www.isotc211.org/2005/gmx&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; xmlns:srv=&quot;http://www.isotc211.org/2005/srv&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CI_Address_Type_Entity {
            get {
                return ResourceManager.GetString("CI_Address_Type_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:Entity xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gmx=&quot;http://www.isotc211.org/2005/gmx&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; xmlns:srv=&quot;http://www.isotc211.org/2005/srv&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CI_Address_Type_Entity_Compact {
            get {
                return ResourceManager.GetString("CI_Address_Type_Entity_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Citation&gt;
        ///  &lt;gmd:title&gt;
        ///    &lt;gco:CharacterString&gt;Geological Indicators of Flooding Great Britain&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:title&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gmd:CI_Date&gt;
        ///      &lt;gmd:date&gt;
        ///        &lt;gco:Date&gt;2006&lt;/gco:Date&gt;
        ///      &lt;/gmd:date&gt;
        ///      &lt;gmd:dateType&gt;
        ///        &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;creation&quot;&gt;creation&lt;/gmd:CI_DateTypeCode&gt;
        ///      &lt;/gmd:dateType&gt;
        ///    &lt;/gmd:CI_Date&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CI_Citation_Type {
            get {
                return ResourceManager.GetString("CI_Citation_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_Contact_PropertyType {
            get {
                return ResourceManager.GetString("CI_Contact_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Contact&gt;
        ///  &lt;gmd:phone&gt;
        ///    &lt;gmd:CI_Telephone&gt;
        ///      &lt;gmd:voice&gt;
        ///        &lt;gco:CharacterString&gt;+44 115 936 3100&lt;/gco:CharacterString&gt;
        ///      &lt;/gmd:voice&gt;
        ///    &lt;/gmd:CI_Telephone&gt;
        ///  &lt;/gmd:phone&gt;
        ///  &lt;gmd:address&gt;
        ///    &lt;gmd:CI_Address&gt;
        ///      &lt;gmd:deliveryPoint&gt;
        ///        &lt;gco:CharacterString&gt;Environmental Science Centre, Keyworth&lt;/gco:CharacterString&gt;
        ///      &lt;/gmd:deliveryPoint&gt;
        ///      &lt;gmd:city&gt;
        ///        &lt;gco:CharacterString&gt;NOTTINGHAM&lt;/gco:CharacterString&gt;
        ///      &lt;/gmd:city&gt;
        ///      &lt;gmd:administra [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CI_Contact_Type {
            get {
                return ResourceManager.GetString("CI_Contact_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_Date_PropertyType {
            get {
                return ResourceManager.GetString("CI_Date_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Date&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gco:Date&gt;2006&lt;/gco:Date&gt;
        ///  &lt;/gmd:date&gt;
        ///  &lt;gmd:dateType&gt;
        ///    &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;creation&quot;&gt;creation&lt;/gmd:CI_DateTypeCode&gt;
        ///  &lt;/gmd:dateType&gt;
        ///&lt;/gmd:CI_Date&gt;.
        /// </summary>
        public static string CI_Date_Type {
            get {
                return ResourceManager.GetString("CI_Date_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;creation&quot;&gt;creation&lt;/gmd:CI_DateTypeCode&gt;.
        /// </summary>
        public static string CI_DateTypeCode_PropertyType {
            get {
                return ResourceManager.GetString("CI_DateTypeCode_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_Individual_PropertyType {
            get {
                return ResourceManager.GetString("CI_Individual_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_Individual_Type {
            get {
                return ResourceManager.GetString("CI_Individual_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_OnLineFunctionCode_PropertyType {
            get {
                return ResourceManager.GetString("CI_OnLineFunctionCode_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_OnlineResource_PropertyType {
            get {
                return ResourceManager.GetString("CI_OnlineResource_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_OnlineResource_Type {
            get {
                return ResourceManager.GetString("CI_OnlineResource_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_Organisation_Type {
            get {
                return ResourceManager.GetString("CI_Organisation_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_PresentationFormCode_PropertyType {
            get {
                return ResourceManager.GetString("CI_PresentationFormCode_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_Responsibility_PropertyType {
            get {
                return ResourceManager.GetString("CI_Responsibility_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_Responsibility_Type {
            get {
                return ResourceManager.GetString("CI_Responsibility_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_ResponsibleParty&gt;
        ///  &lt;gmd:organisationName&gt;
        ///    &lt;gco:CharacterString&gt;British Geological Survey&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:organisationName&gt;
        ///  &lt;gmd:contactInfo&gt;
        ///    &lt;gmd:CI_Contact&gt;
        ///      &lt;gmd:phone&gt;
        ///        &lt;gmd:CI_Telephone&gt;
        ///          &lt;gmd:voice&gt;
        ///            &lt;gco:CharacterString&gt;+44 115 936 3100&lt;/gco:CharacterString&gt;
        ///          &lt;/gmd:voice&gt;
        ///        &lt;/gmd:CI_Telephone&gt;
        ///      &lt;/gmd:phone&gt;
        ///      &lt;gmd:address&gt;
        ///        &lt;gmd:CI_Address&gt;
        ///          &lt;gmd:deliveryPoint&gt;
        ///            &lt;gco:Char [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CI_ResponsiblePartyType {
            get {
                return ResourceManager.GetString("CI_ResponsiblePartyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_RoleCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_RoleCode&quot; codeListValue=&quot;pointOfContact&quot;&gt;pointOfContact&lt;/gmd:CI_RoleCode&gt;.
        /// </summary>
        public static string CI_RoleCode_PropertyType {
            get {
                return ResourceManager.GetString("CI_RoleCode_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_Series_PropertyType {
            get {
                return ResourceManager.GetString("CI_Series_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_Series_Type {
            get {
                return ResourceManager.GetString("CI_Series_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_Telephone_PropertyType {
            get {
                return ResourceManager.GetString("CI_Telephone_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Telephone xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt;
        ///  &lt;gmd:voice&gt;
        ///    &lt;gco:CharacterString xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot;&gt;0115 936 3143&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:voice&gt;
        ///  &lt;gmd:facsimile&gt;
        ///    &lt;gco:CharacterString xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot;&gt;0115 936 3276&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:facsimile&gt;
        ///&lt;/gmd:CI_Telephone&gt;.
        /// </summary>
        public static string CI_Telephone_Type {
            get {
                return ResourceManager.GetString("CI_Telephone_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Telephone xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt;&lt;gmd:voice&gt;&lt;gco:CharacterString xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot;&gt;0115 936 3143&lt;/gco:CharacterString&gt;&lt;/gmd:voice&gt;&lt;gmd:facsimile&gt;&lt;gco:CharacterString xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot;&gt;0115 936 3276&lt;/gco:CharacterString&gt;&lt;/gmd:facsimile&gt;&lt;/gmd:CI_Telephone&gt;.
        /// </summary>
        public static string CI_Telephone_Type_Compact {
            get {
                return ResourceManager.GetString("CI_Telephone_Type_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Telephone xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt;
        ///  &lt;gmd:voice&gt;
        ///    &lt;gco:CharacterString xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot;&gt;+44 115 936 3100&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:voice&gt;
        ///&lt;/gmd:CI_Telephone&gt;.
        /// </summary>
        public static string CI_Telephone_Type2 {
            get {
                return ResourceManager.GetString("CI_Telephone_Type2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Telephone xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt;&lt;gmd:voice&gt;&lt;gco:CharacterString xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot;&gt;+44 115 936 3100&lt;/gco:CharacterString&gt;&lt;/gmd:voice&gt;&lt;/gmd:CI_Telephone&gt;.
        /// </summary>
        public static string CI_Telephone_Type2_Compact {
            get {
                return ResourceManager.GetString("CI_Telephone_Type2_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CI_TelephoneTypeCode_PropertyType {
            get {
                return ResourceManager.GetString("CI_TelephoneTypeCode_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:Entity xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gmx=&quot;http://www.isotc211.org/2005/gmx&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; xmlns:srv=&quot;http://www.isotc211.org/2005/srv&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:Entity xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gmx=&quot;http://www.isotc211.org/2005/gmx&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; xmlns:srv=&quot;http://www.isotc211.org/2005/srv&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Entity_Compact {
            get {
                return ResourceManager.GetString("Entity_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:Entity xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gmx=&quot;http://www.isotc211.org/2005/gmx&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; xmlns:srv=&quot;http://www.isotc211.org/2005/srv&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Entity_Placeholder {
            get {
                return ResourceManager.GetString("Entity_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:Entity xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gmx=&quot;http://www.isotc211.org/2005/gmx&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; xmlns:srv=&quot;http://www.isotc211.org/2005/srv&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Entity_Placeholder_Compact {
            get {
                return ResourceManager.GetString("Entity_Placeholder_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Citation&gt;
        ///  &lt;gmd:title&gt;
        ///    &lt;gco:CharacterString&gt;Geological Indicators of Flooding Great Britain&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:title&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gmd:CI_Date&gt;
        ///      &lt;gmd:date&gt;
        ///        &lt;gco:Date&gt;2006&lt;/gco:Date&gt;
        ///      &lt;/gmd:date&gt;
        ///      &lt;gmd:dateType&gt;
        ///        &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;creation&quot;&gt;creation&lt;/gmd:CI_DateTypeCode&gt;
        ///      &lt;/gmd:dateType&gt;
        ///    &lt;/gmd:CI_Date&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_Citation1 {
            get {
                return ResourceManager.GetString("X_CI_Citation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Citation&gt;
        ///  &lt;gmd:title&gt;
        ///    &lt;gco:CharacterString&gt;GEMET - INSPIRE themes&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:title&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gmd:CI_Date&gt;
        ///      &lt;gmd:date&gt;
        ///        &lt;gco:Date&gt;2008-06-01&lt;/gco:Date&gt;
        ///      &lt;/gmd:date&gt;
        ///      &lt;gmd:dateType&gt;
        ///        &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;publication&quot;&gt;publication&lt;/gmd:CI_DateTypeCode&gt;
        ///      &lt;/gmd:dateType&gt;
        ///    &lt;/gmd:CI_Date&gt;
        ///  &lt;/gmd:date&gt;
        ///&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_Citation2 {
            get {
                return ResourceManager.GetString("X_CI_Citation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Citation&gt;
        ///  &lt;gmd:title&gt;
        ///    &lt;gco:CharacterString&gt;BGS Thesaurus of Geosciences&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:title&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gmd:CI_Date&gt;
        ///      &lt;gmd:date&gt;
        ///        &lt;gco:Date&gt;2011&lt;/gco:Date&gt;
        ///      &lt;/gmd:date&gt;
        ///      &lt;gmd:dateType&gt;
        ///        &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;revision&quot;&gt;revision&lt;/gmd:CI_DateTypeCode&gt;
        ///      &lt;/gmd:dateType&gt;
        ///    &lt;/gmd:CI_Date&gt;
        ///  &lt;/gmd:date&gt;
        ///&lt;/gmd:CI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_Citation3 {
            get {
                return ResourceManager.GetString("X_CI_Citation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Citation&gt;
        ///  &lt;gmd:title&gt;
        ///    &lt;gco:CharacterString&gt;ISO 3166_1 alpha-3&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:title&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gmd:CI_Date&gt;
        ///      &lt;gmd:date&gt;
        ///        &lt;gco:Date&gt;2009&lt;/gco:Date&gt;
        ///      &lt;/gmd:date&gt;
        ///      &lt;gmd:dateType&gt;
        ///        &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;revision&quot;&gt;revision&lt;/gmd:CI_DateTypeCode&gt;
        ///      &lt;/gmd:dateType&gt;
        ///    &lt;/gmd:CI_Date&gt;
        ///  &lt;/gmd:date&gt;
        ///&lt;/gmd:CI_Citation&gt;.
        /// </summary>
        public static string X_CI_Citation4 {
            get {
                return ResourceManager.GetString("X_CI_Citation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Citation&gt;
        ///  &lt;gmd:title&gt;
        ///    &lt;gco:CharacterString&gt;British Geological Survey Gazetteer: Geographical hierarchy from Geosaurus&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:title&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gmd:CI_Date&gt;
        ///      &lt;gmd:date&gt;
        ///        &lt;gco:Date&gt;1979&lt;/gco:Date&gt;
        ///      &lt;/gmd:date&gt;
        ///      &lt;gmd:dateType&gt;
        ///        &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;creation&quot;&gt;creation&lt;/gmd:CI_DateTypeCode&gt;
        ///      &lt;/gmd:dateType [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_Citation5 {
            get {
                return ResourceManager.GetString("X_CI_Citation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Citation&gt;
        ///  &lt;gmd:title&gt;
        ///    &lt;gco:CharacterString&gt;British Geological Survey Gazetteer: Geographical hierarchy from Geosaurus&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:title&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gmd:CI_Date&gt;
        ///      &lt;gmd:date&gt;
        ///        &lt;gco:Date&gt;1979&lt;/gco:Date&gt;
        ///      &lt;/gmd:date&gt;
        ///      &lt;gmd:dateType&gt;
        ///        &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;creation&quot;&gt;creation&lt;/gmd:CI_DateTypeCode&gt;
        ///      &lt;/gmd:dateType [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_Citation6 {
            get {
                return ResourceManager.GetString("X_CI_Citation6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Citation&gt;
        ///  &lt;gmd:title&gt;
        ///    &lt;gco:CharacterString&gt;ISO 3166_1 alpha-3&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:title&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gmd:CI_Date&gt;
        ///      &lt;gmd:date&gt;
        ///        &lt;gco:Date&gt;2009&lt;/gco:Date&gt;
        ///      &lt;/gmd:date&gt;
        ///      &lt;gmd:dateType&gt;
        ///        &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;revision&quot;&gt;revision&lt;/gmd:CI_DateTypeCode&gt;
        ///      &lt;/gmd:dateType&gt;
        ///    &lt;/gmd:CI_Date&gt;
        ///  &lt;/gmd:date&gt;
        ///&lt;/gmd:CI_Citation&gt;.
        /// </summary>
        public static string X_CI_Citation7 {
            get {
                return ResourceManager.GetString("X_CI_Citation7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Citation&gt;
        ///  &lt;gmd:title&gt;
        ///    &lt;gco:CharacterString&gt;British Geological Survey Gazetteer: Geographical hierarchy from Geosaurus&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:title&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gmd:CI_Date&gt;
        ///      &lt;gmd:date&gt;
        ///        &lt;gco:Date&gt;1979&lt;/gco:Date&gt;
        ///      &lt;/gmd:date&gt;
        ///      &lt;gmd:dateType&gt;
        ///        &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;creation&quot;&gt;creation&lt;/gmd:CI_DateTypeCode&gt;
        ///      &lt;/gmd:dateType [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_Citation8 {
            get {
                return ResourceManager.GetString("X_CI_Citation8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_Citation&gt;
        ///  &lt;gmd:title&gt;
        ///    &lt;gco:CharacterString&gt;ISO 3166_1 alpha-3&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:title&gt;
        ///  &lt;gmd:date&gt;
        ///    &lt;gmd:CI_Date&gt;
        ///      &lt;gmd:date&gt;
        ///        &lt;gco:Date&gt;2009&lt;/gco:Date&gt;
        ///      &lt;/gmd:date&gt;
        ///      &lt;gmd:dateType&gt;
        ///        &lt;gmd:CI_DateTypeCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode&quot; codeListValue=&quot;revision&quot;&gt;revision&lt;/gmd:CI_DateTypeCode&gt;
        ///      &lt;/gmd:dateType&gt;
        ///    &lt;/gmd:CI_Date&gt;
        ///  &lt;/gmd:date&gt;
        ///&lt;/gmd:CI_Citation&gt;.
        /// </summary>
        public static string X_CI_Citation9 {
            get {
                return ResourceManager.GetString("X_CI_Citation9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_OnlineResource&gt;
        ///  &lt;gmd:linkage&gt;
        ///    &lt;gmd:URL&gt;http://ogc.bgs.ac.uk/dppp/wmc/gif.xml&lt;/gmd:URL&gt;
        ///  &lt;/gmd:linkage&gt;
        ///  &lt;gmd:protocol&gt;
        ///    &lt;gco:CharacterString&gt;http&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:protocol&gt;
        ///  &lt;gmd:name&gt;
        ///    &lt;gco:CharacterString&gt;Web map context for GIF&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:name&gt;
        ///  &lt;gmd:description&gt;
        ///    &lt;gco:CharacterString&gt;Web map context for GIF&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:description&gt;
        ///  &lt;gmd:function&gt;
        ///    &lt;gmd:CI_OnLineFunctionCode codeList=&quot;https://schemas.isotc211. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_Online_Resource1 {
            get {
                return ResourceManager.GetString("X_CI_Online_Resource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_OnlineResource&gt;
        ///  &lt;gmd:linkage&gt;
        ///    &lt;gmd:URL&gt;http://ogc.bgs.ac.uk/dppp/kml/gif.kml&lt;/gmd:URL&gt;
        ///  &lt;/gmd:linkage&gt;
        ///  &lt;gmd:protocol&gt;
        ///    &lt;gco:CharacterString&gt;http&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:protocol&gt;
        ///  &lt;gmd:name&gt;
        ///    &lt;gco:CharacterString&gt;KML resource for GIF&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:name&gt;
        ///  &lt;gmd:description&gt;
        ///    &lt;gco:CharacterString&gt;KML resource for GIF&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:description&gt;
        ///  &lt;gmd:function&gt;
        ///    &lt;gmd:CI_OnLineFunctionCode codeList=&quot;https://schemas.isotc211.org/sc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_Online_Resource2 {
            get {
                return ResourceManager.GetString("X_CI_Online_Resource2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_OnlineResource&gt;
        ///  &lt;gmd:linkage&gt;
        ///    &lt;gmd:URL&gt;http://www.bgs.ac.uk/products/hydrogeology/indicatorsOfFlooding.html&lt;/gmd:URL&gt;
        ///  &lt;/gmd:linkage&gt;
        ///  &lt;gmd:description&gt;
        ///    &lt;gco:CharacterString&gt;Geological Indicators of Flooding Homepage.&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:description&gt;
        ///  &lt;gmd:function&gt;
        ///    &lt;gmd:CI_OnLineFunctionCode codeList=&quot;https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_OnLineFunctionCode&quot; codeListValue=&quot;information&quot;&gt;information&lt;/gmd:CI_OnLineFunctionC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_Online_Resource3 {
            get {
                return ResourceManager.GetString("X_CI_Online_Resource3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_ResponsibleParty&gt;
        ///  &lt;gmd:individualName&gt;
        ///    &lt;gco:CharacterString&gt;Enquiries&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:individualName&gt;
        ///  &lt;gmd:organisationName&gt;
        ///    &lt;gco:CharacterString&gt;British Geological Survey&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:organisationName&gt;
        ///  &lt;gmd:contactInfo&gt;
        ///    &lt;gmd:CI_Contact&gt;
        ///      &lt;gmd:phone&gt;
        ///        &lt;gmd:CI_Telephone&gt;
        ///          &lt;gmd:voice&gt;
        ///            &lt;gco:CharacterString&gt;0115 936 3143&lt;/gco:CharacterString&gt;
        ///          &lt;/gmd:voice&gt;
        ///          &lt;gmd:facsimile&gt;
        ///            &lt;gco: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_ResponsibleParty1 {
            get {
                return ResourceManager.GetString("X_CI_ResponsibleParty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_ResponsibleParty&gt;
        ///  &lt;gmd:individualName&gt;
        ///    &lt;gco:CharacterString&gt;Enquiries&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:individualName&gt;
        ///  &lt;gmd:organisationName&gt;
        ///    &lt;gco:CharacterString&gt;British Geological Survey&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:organisationName&gt;
        ///  &lt;gmd:contactInfo&gt;
        ///    &lt;gmd:CI_Contact&gt;
        ///      &lt;gmd:phone&gt;
        ///        &lt;gmd:CI_Telephone&gt;
        ///          &lt;gmd:voice&gt;
        ///            &lt;gco:CharacterString&gt;0115 936 3143&lt;/gco:CharacterString&gt;
        ///          &lt;/gmd:voice&gt;
        ///          &lt;gmd:facsimile&gt;
        ///            &lt;gco: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_ResponsibleParty2 {
            get {
                return ResourceManager.GetString("X_CI_ResponsibleParty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_ResponsibleParty&gt;
        ///  &lt;gmd:individualName&gt;
        ///    &lt;gco:CharacterString&gt;Enquiries&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:individualName&gt;
        ///  &lt;gmd:organisationName&gt;
        ///    &lt;gco:CharacterString&gt;British Geological Survey&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:organisationName&gt;
        ///  &lt;gmd:contactInfo&gt;
        ///    &lt;gmd:CI_Contact&gt;
        ///      &lt;gmd:phone&gt;
        ///        &lt;gmd:CI_Telephone&gt;
        ///          &lt;gmd:voice&gt;
        ///            &lt;gco:CharacterString&gt;0115 936 3143&lt;/gco:CharacterString&gt;
        ///          &lt;/gmd:voice&gt;
        ///          &lt;gmd:facsimile&gt;
        ///            &lt;gco: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_ResponsibleParty3 {
            get {
                return ResourceManager.GetString("X_CI_ResponsibleParty3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gmd:CI_ResponsibleParty&gt;
        ///  &lt;gmd:organisationName&gt;
        ///    &lt;gco:CharacterString&gt;British Geological Survey&lt;/gco:CharacterString&gt;
        ///  &lt;/gmd:organisationName&gt;
        ///  &lt;gmd:contactInfo&gt;
        ///    &lt;gmd:CI_Contact&gt;
        ///      &lt;gmd:phone&gt;
        ///        &lt;gmd:CI_Telephone&gt;
        ///          &lt;gmd:voice&gt;
        ///            &lt;gco:CharacterString&gt;+44 115 936 3100&lt;/gco:CharacterString&gt;
        ///          &lt;/gmd:voice&gt;
        ///        &lt;/gmd:CI_Telephone&gt;
        ///      &lt;/gmd:phone&gt;
        ///      &lt;gmd:address&gt;
        ///        &lt;gmd:CI_Address&gt;
        ///          &lt;gmd:deliveryPoint&gt;
        ///            &lt;gco:Char [rest of string was truncated]&quot;;.
        /// </summary>
        public static string X_CI_ResponsibleParty4 {
            get {
                return ResourceManager.GetString("X_CI_ResponsibleParty4", resourceCulture);
            }
        }
    }
}
