// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.74.0. www.xsd2code.com
//    {"TargetFramework":"NetStandard","NameSpace":"NDSH.Geospatial.Metadata","GenerateUnusedComplexType":true,"GenerateUnusedSimpleType":true,"Properties":{"NotifyPropertyChanged":true},"XmlAttribute":{"Enabled":true,"GenerateOrderXmlAttributes":true},"JsonAttribute":{"Enabled":true,"MemberName":1},"DataAnnotationsAttribute":{"StringLengthAttribute":true,"Required":true,"MaxLengthAttribute":true,"MinLengthAttribute":true,"RegularExpressionAttribute":true,"RangeAttribute":true,"MaxDigitsAttribute":true,"FractionDigitsAttribute":true,"DefautValueAttribute":true,"ValidatePropertyInSetter":true,"Enabled":true},"ClassParams":{"PartialClass":false,"GenerateInSeparateFilesDirectory":""},"Miscellaneous":{"EnableSummaryComment":true}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
using NDSH.Geospatial.Metadata.V19136.GML;
using NDSH.Geospatial.Metadata.V19136.GML.BasicTypes;

namespace AAAA {
  using NDSH.Geospatial.Metadata.V19136;
  using System;
  using System.Diagnostics;
  using System.Xml.Serialization;
  using System.Runtime.Serialization;
  using System.Collections;
  using System.Xml.Schema;
  using System.ComponentModel;
  using System.Globalization;
  using System.Xml;
  using System.ComponentModel.DataAnnotations;
  using System.Collections.Generic;
  using Newtonsoft.Json;
  using Newtonsoft.Json.Converters;
  using System.Runtime.CompilerServices;
  using NDSH.Geospatial.Metadata.V19136.ConceptualSchema;
  using NDSH.Geospatial.Metadata.V19136.EntitySet;
  using NDSH.Geospatial.Metadata.V19136.ConceptualSchema.Implementation.Names;
  using NDSH.Geospatial.Metadata.V19136.Common.Citation;
  using NDSH.Geospatial.Metadata.V19136.ConceptualSchema.Primitive.Text;
  using NDSH.Geospatial.Metadata.V19136.ConceptualSchema.Primitive.Truth;
  using Boolean = NDSH.Geospatial.Metadata.V19136.GML.BasicTypes.Boolean;
  using NDSH.Geospatial.Metadata.V19136.ConceptualSchema.Primitive.Numerics;
  using NDSH.Geospatial.Metadata.V19136.DataQuality;
  using NDSH.Geospatial.Metadata.V19136.Distribution;
  using NDSH.Geospatial.Metadata.V19136.Common.Extent;
  using NDSH.Geospatial.Metadata.V19136.Content;
  using NDSH.Geospatial.Metadata.V19136.Constraint;
  using NDSH.Geospatial.Metadata.V19136.GML.Measures;
  using NDSH.Geospatial.Metadata.V19136.Common;
  using NDSH.Geospatial.Metadata.V19136.DataQuality.PositionalAccuracy;
  using NDSH.Geospatial.Metadata.V19136.GML.Base;
  using NDSH.Geospatial.Metadata.V19136.ReferenceSystem;
  using NDSH.Geospatial.Metadata.V19136.GML.CoordinateReferenceSystems.CoordinateSystems;
  using NDSH.Geospatial.Metadata.V19136.GML.DynamicFeature;
  using NDSH.Geospatial.Metadata.V19136.GML.Observation;
  using NDSH.Geospatial.Metadata.V19136.GML.Coverage;
  using NDSH.Geospatial.Metadata.V19136.GML.CoordinateReferenceSystems.Datums;
  using NDSH.Geospatial.Metadata.V19136.GML.TemporalTopology;
  using NDSH.Geospatial.Metadata.V19136.GML.Temporal;
  using NDSH.Geospatial.Metadata.V19136.GML.Units;
  using NDSH.Geospatial.Metadata.V19136.GML.Dictionary;
  using NDSH.Geospatial.Metadata.V19136.GML.GeometryPrimitives;
  using NDSH.Geospatial.Metadata.V19136.GML.GeometryBasic0d1d;




}
#pragma warning restore