### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
  id: Implementation.Names
  parent: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema
  children:
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.CodeConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.LocalNameConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.TypeNameConfiguration
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.ISO19115.Ed2003.DB
references:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.CodeConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.CodeConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.CodeConfiguration.html
  name: CodeConfiguration
  nameWithType: CodeConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.CodeConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.LocalNameConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.LocalNameConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.LocalNameConfiguration.html
  name: LocalNameConfiguration
  nameWithType: LocalNameConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.LocalNameConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.TypeNameConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.TypeNameConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.TypeNameConfiguration.html
  name: TypeNameConfiguration
  nameWithType: TypeNameConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Implementation.Names.TypeNameConfiguration
