### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.Metadata.V2005.ApplicationSchema
  commentId: N:NDSH.Geospatial.Metadata.V2005.ApplicationSchema
  id: ApplicationSchema
  parent: NDSH.Geospatial.Metadata.V2005
  children:
  - NDSH.Geospatial.Metadata.V2005.ApplicationSchema.MD_ApplicationSchemaInformation
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.Metadata.V2005.ApplicationSchema
  nameWithType: NDSH.Geospatial.Metadata.V2005.ApplicationSchema
  fullName: NDSH.Geospatial.Metadata.V2005.ApplicationSchema
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.V2005
references:
- uid: NDSH.Geospatial.Metadata.V2005.ApplicationSchema.MD_ApplicationSchemaInformation
  commentId: T:NDSH.Geospatial.Metadata.V2005.ApplicationSchema.MD_ApplicationSchemaInformation
  href: NDSH.Geospatial.Metadata.V2005.ApplicationSchema.MD_ApplicationSchemaInformation.html
  name: MD_ApplicationSchemaInformation
  nameWithType: MD_ApplicationSchemaInformation
  fullName: NDSH.Geospatial.Metadata.V2005.ApplicationSchema.MD_ApplicationSchemaInformation
