### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
  id: Lineage
  parent: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality
  children:
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage.LiLineageConfiguration
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.ISO19115.Ed2003.DB
references:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage.LiLineageConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage.LiLineageConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage.LiLineageConfiguration.html
  name: LiLineageConfiguration
  nameWithType: LiLineageConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage.LiLineageConfiguration
