### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.Metadata.ApplicationSchema
  commentId: N:NDSH.Geospatial.Metadata.ApplicationSchema
  id: ApplicationSchema
  parent: NDSH.Geospatial.Metadata
  children:
  - NDSH.Geospatial.Metadata.ApplicationSchema.MD_ApplicationSchemaInformation_Type
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.Metadata.ApplicationSchema
  nameWithType: NDSH.Geospatial.Metadata.ApplicationSchema
  fullName: NDSH.Geospatial.Metadata.ApplicationSchema
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.ISO19115.Ed2003
references:
- uid: NDSH.Geospatial.Metadata.ApplicationSchema.MD_ApplicationSchemaInformation_Type
  commentId: T:NDSH.Geospatial.Metadata.ApplicationSchema.MD_ApplicationSchemaInformation_Type
  href: NDSH.Geospatial.Metadata.ApplicationSchema.MD_ApplicationSchemaInformation_Type.html
  name: MD_ApplicationSchemaInformation_Type
  nameWithType: MD_ApplicationSchemaInformation_Type
  fullName: NDSH.Geospatial.Metadata.ApplicationSchema.MD_ApplicationSchemaInformation_Type
