### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification
  id: Identification
  parent: NDSH.Geospatial.MetadataDB.Relational.Configurations
  children:
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.AbstractMdIdentificationConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdAggregateInformationConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdBrowseGraphicConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdDataIdentificationConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdKeywordsConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdRepresentativeFractionConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdResolutionConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdTopicCategoryCodeDbEntityConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdUsageConfiguration
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.ISO19115.Ed2003.DB
references:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.AbstractMdIdentificationConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.AbstractMdIdentificationConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.AbstractMdIdentificationConfiguration.html
  name: AbstractMdIdentificationConfiguration
  nameWithType: AbstractMdIdentificationConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.AbstractMdIdentificationConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdAggregateInformationConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdAggregateInformationConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdAggregateInformationConfiguration.html
  name: MdAggregateInformationConfiguration
  nameWithType: MdAggregateInformationConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdAggregateInformationConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdBrowseGraphicConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdBrowseGraphicConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdBrowseGraphicConfiguration.html
  name: MdBrowseGraphicConfiguration
  nameWithType: MdBrowseGraphicConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdBrowseGraphicConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdDataIdentificationConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdDataIdentificationConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdDataIdentificationConfiguration.html
  name: MdDataIdentificationConfiguration
  nameWithType: MdDataIdentificationConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdDataIdentificationConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdKeywordsConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdKeywordsConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdKeywordsConfiguration.html
  name: MdKeywordsConfiguration
  nameWithType: MdKeywordsConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdKeywordsConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdRepresentativeFractionConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdRepresentativeFractionConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdRepresentativeFractionConfiguration.html
  name: MdRepresentativeFractionConfiguration
  nameWithType: MdRepresentativeFractionConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdRepresentativeFractionConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdResolutionConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdResolutionConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdResolutionConfiguration.html
  name: MdResolutionConfiguration
  nameWithType: MdResolutionConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdResolutionConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdTopicCategoryCodeDbEntityConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdTopicCategoryCodeDbEntityConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdTopicCategoryCodeDbEntityConfiguration.html
  name: MdTopicCategoryCodeDbEntityConfiguration
  nameWithType: MdTopicCategoryCodeDbEntityConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdTopicCategoryCodeDbEntityConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdUsageConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdUsageConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdUsageConfiguration.html
  name: MdUsageConfiguration
  nameWithType: MdUsageConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Identification.MdUsageConfiguration
