### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.Metadata.V2003.ApplicationSchema
  commentId: N:NDSH.Geospatial.Metadata.V2003.ApplicationSchema
  id: ApplicationSchema
  parent: NDSH.Geospatial.Metadata.V2003
  children:
  - NDSH.Geospatial.Metadata.V2003.ApplicationSchema.MD_ApplicationSchemaInformation_PropertyType
  - NDSH.Geospatial.Metadata.V2003.ApplicationSchema.MD_ApplicationSchemaInformation_Type
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.Metadata.V2003.ApplicationSchema
  nameWithType: NDSH.Geospatial.Metadata.V2003.ApplicationSchema
  fullName: NDSH.Geospatial.Metadata.V2003.ApplicationSchema
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.V2003
references:
- uid: NDSH.Geospatial.Metadata.V2003.ApplicationSchema.MD_ApplicationSchemaInformation_PropertyType
  commentId: T:NDSH.Geospatial.Metadata.V2003.ApplicationSchema.MD_ApplicationSchemaInformation_PropertyType
  href: NDSH.Geospatial.Metadata.V2003.ApplicationSchema.MD_ApplicationSchemaInformation_PropertyType.html
  name: MD_ApplicationSchemaInformation_PropertyType
  nameWithType: MD_ApplicationSchemaInformation_PropertyType
  fullName: NDSH.Geospatial.Metadata.V2003.ApplicationSchema.MD_ApplicationSchemaInformation_PropertyType
- uid: NDSH.Geospatial.Metadata.V2003.ApplicationSchema.MD_ApplicationSchemaInformation_Type
  commentId: T:NDSH.Geospatial.Metadata.V2003.ApplicationSchema.MD_ApplicationSchemaInformation_Type
  parent: NDSH.Geospatial.Metadata.V2003.ApplicationSchema
  href: NDSH.Geospatial.Metadata.V2003.ApplicationSchema.MD_ApplicationSchemaInformation_Type.html
  name: MD_ApplicationSchemaInformation_Type
  nameWithType: MD_ApplicationSchemaInformation_Type
  fullName: NDSH.Geospatial.Metadata.V2003.ApplicationSchema.MD_ApplicationSchemaInformation_Type
- uid: NDSH.Geospatial.Metadata.V2003.ApplicationSchema
  commentId: N:NDSH.Geospatial.Metadata.V2003.ApplicationSchema
  href: NDSH.html
  name: NDSH.Geospatial.Metadata.V2003.ApplicationSchema
  nameWithType: NDSH.Geospatial.Metadata.V2003.ApplicationSchema
  fullName: NDSH.Geospatial.Metadata.V2003.ApplicationSchema
  spec.csharp:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Metadata
    name: Metadata
    href: NDSH.Geospatial.Metadata.html
  - name: .
  - uid: NDSH.Geospatial.Metadata.V2003
    name: V2003
    href: NDSH.Geospatial.Metadata.V2003.html
  - name: .
  - uid: NDSH.Geospatial.Metadata.V2003.ApplicationSchema
    name: ApplicationSchema
    href: NDSH.Geospatial.Metadata.V2003.ApplicationSchema.html
  spec.vb:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Metadata
    name: Metadata
    href: NDSH.Geospatial.Metadata.html
  - name: .
  - uid: NDSH.Geospatial.Metadata.V2003
    name: V2003
    href: NDSH.Geospatial.Metadata.V2003.html
  - name: .
  - uid: NDSH.Geospatial.Metadata.V2003.ApplicationSchema
    name: ApplicationSchema
    href: NDSH.Geospatial.Metadata.V2003.ApplicationSchema.html
