### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.Metadata.Application
  commentId: N:NDSH.Geospatial.Metadata.Application
  id: Application
  parent: NDSH.Geospatial.Metadata
  children:
  - NDSH.Geospatial.Metadata.Application.AbstractDS_Aggregate_Type
  - NDSH.Geospatial.Metadata.Application.DS_DataSet_Type
  - NDSH.Geospatial.Metadata.Application.DS_Initiative_Type
  - NDSH.Geospatial.Metadata.Application.DS_OtherAggregate_Type
  - NDSH.Geospatial.Metadata.Application.DS_Platform_Type
  - NDSH.Geospatial.Metadata.Application.DS_ProductionSeries_Type
  - NDSH.Geospatial.Metadata.Application.DS_Sensor_Type
  - NDSH.Geospatial.Metadata.Application.DS_Series_Type
  - NDSH.Geospatial.Metadata.Application.DS_StereoMate_Type
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.Metadata.Application
  nameWithType: NDSH.Geospatial.Metadata.Application
  fullName: NDSH.Geospatial.Metadata.Application
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.ISO19115.Ed2003
references:
- uid: NDSH.Geospatial.Metadata.Application.AbstractDS_Aggregate_Type
  commentId: T:NDSH.Geospatial.Metadata.Application.AbstractDS_Aggregate_Type
  parent: NDSH.Geospatial.Metadata.Application
  href: NDSH.Geospatial.Metadata.Application.AbstractDS_Aggregate_Type.html
  name: AbstractDS_Aggregate_Type
  nameWithType: AbstractDS_Aggregate_Type
  fullName: NDSH.Geospatial.Metadata.Application.AbstractDS_Aggregate_Type
- uid: NDSH.Geospatial.Metadata.Application.DS_DataSet_Type
  commentId: T:NDSH.Geospatial.Metadata.Application.DS_DataSet_Type
  parent: NDSH.Geospatial.Metadata.Application
  href: NDSH.Geospatial.Metadata.Application.DS_DataSet_Type.html
  name: DS_DataSet_Type
  nameWithType: DS_DataSet_Type
  fullName: NDSH.Geospatial.Metadata.Application.DS_DataSet_Type
- uid: NDSH.Geospatial.Metadata.Application.DS_Initiative_Type
  commentId: T:NDSH.Geospatial.Metadata.Application.DS_Initiative_Type
  href: NDSH.Geospatial.Metadata.Application.DS_Initiative_Type.html
  name: DS_Initiative_Type
  nameWithType: DS_Initiative_Type
  fullName: NDSH.Geospatial.Metadata.Application.DS_Initiative_Type
- uid: NDSH.Geospatial.Metadata.Application.DS_OtherAggregate_Type
  commentId: T:NDSH.Geospatial.Metadata.Application.DS_OtherAggregate_Type
  parent: NDSH.Geospatial.Metadata.Application
  href: NDSH.Geospatial.Metadata.Application.DS_OtherAggregate_Type.html
  name: DS_OtherAggregate_Type
  nameWithType: DS_OtherAggregate_Type
  fullName: NDSH.Geospatial.Metadata.Application.DS_OtherAggregate_Type
- uid: NDSH.Geospatial.Metadata.Application.DS_Platform_Type
  commentId: T:NDSH.Geospatial.Metadata.Application.DS_Platform_Type
  href: NDSH.Geospatial.Metadata.Application.DS_Platform_Type.html
  name: DS_Platform_Type
  nameWithType: DS_Platform_Type
  fullName: NDSH.Geospatial.Metadata.Application.DS_Platform_Type
- uid: NDSH.Geospatial.Metadata.Application.DS_ProductionSeries_Type
  commentId: T:NDSH.Geospatial.Metadata.Application.DS_ProductionSeries_Type
  href: NDSH.Geospatial.Metadata.Application.DS_ProductionSeries_Type.html
  name: DS_ProductionSeries_Type
  nameWithType: DS_ProductionSeries_Type
  fullName: NDSH.Geospatial.Metadata.Application.DS_ProductionSeries_Type
- uid: NDSH.Geospatial.Metadata.Application.DS_Sensor_Type
  commentId: T:NDSH.Geospatial.Metadata.Application.DS_Sensor_Type
  href: NDSH.Geospatial.Metadata.Application.DS_Sensor_Type.html
  name: DS_Sensor_Type
  nameWithType: DS_Sensor_Type
  fullName: NDSH.Geospatial.Metadata.Application.DS_Sensor_Type
- uid: NDSH.Geospatial.Metadata.Application.DS_Series_Type
  commentId: T:NDSH.Geospatial.Metadata.Application.DS_Series_Type
  parent: NDSH.Geospatial.Metadata.Application
  href: NDSH.Geospatial.Metadata.Application.DS_Series_Type.html
  name: DS_Series_Type
  nameWithType: DS_Series_Type
  fullName: NDSH.Geospatial.Metadata.Application.DS_Series_Type
- uid: NDSH.Geospatial.Metadata.Application.DS_StereoMate_Type
  commentId: T:NDSH.Geospatial.Metadata.Application.DS_StereoMate_Type
  href: NDSH.Geospatial.Metadata.Application.DS_StereoMate_Type.html
  name: DS_StereoMate_Type
  nameWithType: DS_StereoMate_Type
  fullName: NDSH.Geospatial.Metadata.Application.DS_StereoMate_Type
- uid: NDSH.Geospatial.Metadata.Application
  commentId: N:NDSH.Geospatial.Metadata.Application
  href: NDSH.html
  name: NDSH.Geospatial.Metadata.Application
  nameWithType: NDSH.Geospatial.Metadata.Application
  fullName: NDSH.Geospatial.Metadata.Application
  spec.csharp:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Metadata
    name: Metadata
    href: NDSH.Geospatial.Metadata.html
  - name: .
  - uid: NDSH.Geospatial.Metadata.Application
    name: Application
    href: NDSH.Geospatial.Metadata.Application.html
  spec.vb:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Metadata
    name: Metadata
    href: NDSH.Geospatial.Metadata.html
  - name: .
  - uid: NDSH.Geospatial.Metadata.Application
    name: Application
    href: NDSH.Geospatial.Metadata.Application.html
