### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality
  id: DataQuality
  parent: NDSH.Geospatial.MetadataDB.Relational.Configurations
  children:
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.AbstractDqResultConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqConformanceResultConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqDataQualityConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqScopeConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.ISO19115.Ed2003.DB
references:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
  href: NDSH.html
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
  spec.csharp:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB
    name: MetadataDB
    href: NDSH.Geospatial.MetadataDB.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational
    name: Relational
    href: NDSH.Geospatial.MetadataDB.Relational.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations
    name: Configurations
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality
    name: DataQuality
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
    name: Lineage
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage.html
  spec.vb:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB
    name: MetadataDB
    href: NDSH.Geospatial.MetadataDB.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational
    name: Relational
    href: NDSH.Geospatial.MetadataDB.Relational.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations
    name: Configurations
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality
    name: DataQuality
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.html
  - name: .
  - uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage
    name: Lineage
    href: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.Lineage.html
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.AbstractDqResultConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.AbstractDqResultConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.AbstractDqResultConfiguration.html
  name: AbstractDqResultConfiguration
  nameWithType: AbstractDqResultConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.AbstractDqResultConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqConformanceResultConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqConformanceResultConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqConformanceResultConfiguration.html
  name: DqConformanceResultConfiguration
  nameWithType: DqConformanceResultConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqConformanceResultConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqDataQualityConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqDataQualityConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqDataQualityConfiguration.html
  name: DqDataQualityConfiguration
  nameWithType: DqDataQualityConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqDataQualityConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqScopeConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqScopeConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqScopeConfiguration.html
  name: DqScopeConfiguration
  nameWithType: DqScopeConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.DataQuality.DqScopeConfiguration
