### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem
  id: ReferenceSystem
  parent: NDSH.Geospatial.MetadataDB.Relational.Configurations
  children:
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.MdIdentifierConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.MdReferenceSystemConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.RsIdentifierConfiguration
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.ISO19115.Ed2003.DB
references:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.MdIdentifierConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.MdIdentifierConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.MdIdentifierConfiguration.html
  name: MdIdentifierConfiguration
  nameWithType: MdIdentifierConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.MdIdentifierConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.MdReferenceSystemConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.MdReferenceSystemConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.MdReferenceSystemConfiguration.html
  name: MdReferenceSystemConfiguration
  nameWithType: MdReferenceSystemConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.MdReferenceSystemConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.RsIdentifierConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.RsIdentifierConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.RsIdentifierConfiguration.html
  name: RsIdentifierConfiguration
  nameWithType: RsIdentifierConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ReferenceSystem.RsIdentifierConfiguration
