### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel
  commentId: T:NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel
  id: ApplicationModel
  parent: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
  children:
  - NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.ArcGISApiKey
  - NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.DatabaseConnectionsInfo
  - NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.Service
  langs:
  - csharp
  - vb
  name: ApplicationModel
  nameWithType: ApplicationModel
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel
  type: Class
  source:
    remote:
      path: Proj/src/src/NDSH.Geospatial.Demos.SearchAndMap.Blazor/src/Models/ApplicationModel.cs
      branch: dev
      repo: https://github.com/NERC-Digital-Solutions-Hub/ndsh-dotnet-temp.git
    id: ApplicationModel
    path: ../../../GitHub/ndsh-dotnet-temp/dev/Proj/src/src/NDSH.Geospatial.Demos.SearchAndMap.Blazor/src/Models/ApplicationModel.cs
    startLine: 15
  assemblies:
  - NDSH.Geospatial.Demos.SearchAndMap.Blazor
  namespace: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
  summary: The model of the application.
  example: []
  syntax:
    content: 'public sealed class ApplicationModel : Model, IModel, INotifyPropertyChanged'
    content.vb: Public NotInheritable Class ApplicationModel Inherits Model Implements IModel, INotifyPropertyChanged
  inheritance:
  - System.Object
  - NDSH.Geospatial.Demos.SearchAndMap.Model
  implements:
  - NDSH.Geospatial.Demos.SearchAndMap.IModel
  - INotifyPropertyChanged
  inheritedMembers:
  - NDSH.Geospatial.Demos.SearchAndMap.Model.PropertyChanged
- uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.ArcGISApiKey
  commentId: P:NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.ArcGISApiKey
  id: ArcGISApiKey
  parent: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel
  langs:
  - csharp
  - vb
  name: ArcGISApiKey
  nameWithType: ApplicationModel.ArcGISApiKey
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.ArcGISApiKey
  type: Property
  source:
    remote:
      path: Proj/src/src/NDSH.Geospatial.Demos.SearchAndMap.Blazor/src/Models/ApplicationModel.cs
      branch: dev
      repo: https://github.com/NERC-Digital-Solutions-Hub/ndsh-dotnet-temp.git
    id: ArcGISApiKey
    path: ../../../GitHub/ndsh-dotnet-temp/dev/Proj/src/src/NDSH.Geospatial.Demos.SearchAndMap.Blazor/src/Models/ApplicationModel.cs
    startLine: 24
  assemblies:
  - NDSH.Geospatial.Demos.SearchAndMap.Blazor
  namespace: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
  summary: Gets/Sets the ArcGIS Online API Key.
  example: []
  syntax:
    content: public string ArcGISApiKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ArcGISApiKey As String
  overload: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.ArcGISApiKey*
- uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.DatabaseConnectionsInfo
  commentId: P:NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.DatabaseConnectionsInfo
  id: DatabaseConnectionsInfo
  parent: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel
  langs:
  - csharp
  - vb
  name: DatabaseConnectionsInfo
  nameWithType: ApplicationModel.DatabaseConnectionsInfo
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.DatabaseConnectionsInfo
  type: Property
  source:
    remote:
      path: Proj/src/src/NDSH.Geospatial.Demos.SearchAndMap.Blazor/src/Models/ApplicationModel.cs
      branch: dev
      repo: https://github.com/NERC-Digital-Solutions-Hub/ndsh-dotnet-temp.git
    id: DatabaseConnectionsInfo
    path: ../../../GitHub/ndsh-dotnet-temp/dev/Proj/src/src/NDSH.Geospatial.Demos.SearchAndMap.Blazor/src/Models/ApplicationModel.cs
    startLine: 42
  assemblies:
  - NDSH.Geospatial.Demos.SearchAndMap.Blazor
  namespace: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
  summary: >-
    Gets/Sets the ObservableCollection&lt;T&gt; of

    Database.DatabaseConnectionInfo.
  example: []
  syntax:
    content: public ObservableCollection<DatabaseConnectionInfo> DatabaseConnectionsInfo { get; set; }
    parameters: []
    return:
      type: ObservableCollection{DatabaseConnectionInfo}
    content.vb: Public Property DatabaseConnectionsInfo As ObservableCollection(Of DatabaseConnectionInfo)
  overload: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.DatabaseConnectionsInfo*
- uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.Service
  commentId: P:NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.Service
  id: Service
  parent: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel
  langs:
  - csharp
  - vb
  name: Service
  nameWithType: ApplicationModel.Service
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.Service
  type: Property
  source:
    remote:
      path: Proj/src/src/NDSH.Geospatial.Demos.SearchAndMap.Blazor/src/Models/ApplicationModel.cs
      branch: dev
      repo: https://github.com/NERC-Digital-Solutions-Hub/ndsh-dotnet-temp.git
    id: Service
    path: ../../../GitHub/ndsh-dotnet-temp/dev/Proj/src/src/NDSH.Geospatial.Demos.SearchAndMap.Blazor/src/Models/ApplicationModel.cs
    startLine: 58
  assemblies:
  - NDSH.Geospatial.Demos.SearchAndMap.Blazor
  namespace: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
  summary: Gets/Sets the Services.MetadataSemanticSearch.Service
  example: []
  syntax:
    content: public Service Service { get; set; }
    parameters: []
    return:
      type: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch.Service
    content.vb: Public Property Service As Service
  overload: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.Service*
references:
- uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
  commentId: N:NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
  href: NDSH.html
  name: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
  nameWithType: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
  spec.csharp:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Demos
    name: Demos
    href: NDSH.Geospatial.Demos.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap
    name: SearchAndMap
    href: NDSH.Geospatial.Demos.SearchAndMap.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor
    name: Blazor
    href: NDSH.Geospatial.Demos.SearchAndMap.Blazor.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
    name: Models
    href: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.html
  spec.vb:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Demos
    name: Demos
    href: NDSH.Geospatial.Demos.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap
    name: SearchAndMap
    href: NDSH.Geospatial.Demos.SearchAndMap.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor
    name: Blazor
    href: NDSH.Geospatial.Demos.SearchAndMap.Blazor.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models
    name: Models
    href: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: NDSH.Geospatial.Demos.SearchAndMap.Model
  commentId: T:NDSH.Geospatial.Demos.SearchAndMap.Model
  parent: NDSH.Geospatial.Demos.SearchAndMap
  href: NDSH.Geospatial.Demos.SearchAndMap.Model.html
  name: Model
  nameWithType: Model
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Model
- uid: NDSH.Geospatial.Demos.SearchAndMap.IModel
  commentId: T:NDSH.Geospatial.Demos.SearchAndMap.IModel
  parent: NDSH.Geospatial.Demos.SearchAndMap
  href: NDSH.Geospatial.Demos.SearchAndMap.IModel.html
  name: IModel
  nameWithType: IModel
  fullName: NDSH.Geospatial.Demos.SearchAndMap.IModel
- uid: INotifyPropertyChanged
  isExternal: true
  name: INotifyPropertyChanged
  nameWithType: INotifyPropertyChanged
  fullName: INotifyPropertyChanged
- uid: NDSH.Geospatial.Demos.SearchAndMap.Model.PropertyChanged
  commentId: E:NDSH.Geospatial.Demos.SearchAndMap.Model.PropertyChanged
  parent: NDSH.Geospatial.Demos.SearchAndMap.Model
  href: NDSH.Geospatial.Demos.SearchAndMap.Model.html#NDSH_Geospatial_Demos_SearchAndMap_Model_PropertyChanged
  name: PropertyChanged
  nameWithType: Model.PropertyChanged
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Model.PropertyChanged
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: NDSH.Geospatial.Demos.SearchAndMap
  commentId: N:NDSH.Geospatial.Demos.SearchAndMap
  href: NDSH.html
  name: NDSH.Geospatial.Demos.SearchAndMap
  nameWithType: NDSH.Geospatial.Demos.SearchAndMap
  fullName: NDSH.Geospatial.Demos.SearchAndMap
  spec.csharp:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Demos
    name: Demos
    href: NDSH.Geospatial.Demos.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap
    name: SearchAndMap
    href: NDSH.Geospatial.Demos.SearchAndMap.html
  spec.vb:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Demos
    name: Demos
    href: NDSH.Geospatial.Demos.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap
    name: SearchAndMap
    href: NDSH.Geospatial.Demos.SearchAndMap.html
- uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.ArcGISApiKey*
  commentId: Overload:NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.ArcGISApiKey
  href: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.html#NDSH_Geospatial_Demos_SearchAndMap_Blazor_Models_ApplicationModel_ArcGISApiKey
  name: ArcGISApiKey
  nameWithType: ApplicationModel.ArcGISApiKey
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.ArcGISApiKey
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.DatabaseConnectionsInfo*
  commentId: Overload:NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.DatabaseConnectionsInfo
  href: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.html#NDSH_Geospatial_Demos_SearchAndMap_Blazor_Models_ApplicationModel_DatabaseConnectionsInfo
  name: DatabaseConnectionsInfo
  nameWithType: ApplicationModel.DatabaseConnectionsInfo
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.DatabaseConnectionsInfo
- uid: ObservableCollection{DatabaseConnectionInfo}
  commentId: '!:ObservableCollection{DatabaseConnectionInfo}'
  definition: ObservableCollection`1
  name: ObservableCollection<DatabaseConnectionInfo>
  nameWithType: ObservableCollection<DatabaseConnectionInfo>
  fullName: ObservableCollection<DatabaseConnectionInfo>
  nameWithType.vb: ObservableCollection(Of DatabaseConnectionInfo)
  fullName.vb: ObservableCollection(Of DatabaseConnectionInfo)
  name.vb: ObservableCollection(Of DatabaseConnectionInfo)
  spec.csharp:
  - uid: ObservableCollection`1
    name: ObservableCollection
    isExternal: true
  - name: <
  - uid: DatabaseConnectionInfo
    name: DatabaseConnectionInfo
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: ObservableCollection`1
    name: ObservableCollection
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: DatabaseConnectionInfo
    name: DatabaseConnectionInfo
    isExternal: true
  - name: )
- uid: ObservableCollection`1
  isExternal: true
  name: ObservableCollection<>
  nameWithType: ObservableCollection<>
  fullName: ObservableCollection<>
  nameWithType.vb: ObservableCollection(Of )
  fullName.vb: ObservableCollection(Of )
  name.vb: ObservableCollection(Of )
  spec.csharp:
  - uid: ObservableCollection`1
    name: ObservableCollection
    isExternal: true
  - name: <
  - name: ''
  - name: '>'
  spec.vb:
  - uid: ObservableCollection`1
    name: ObservableCollection
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: ''
  - name: )
- uid: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.Service*
  commentId: Overload:NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.Service
  href: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.html#NDSH_Geospatial_Demos_SearchAndMap_Blazor_Models_ApplicationModel_Service
  name: Service
  nameWithType: ApplicationModel.Service
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Blazor.Models.ApplicationModel.Service
- uid: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch.Service
  commentId: T:NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch.Service
  parent: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch
  href: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch.Service.html
  name: Service
  nameWithType: Service
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch.Service
- uid: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch
  commentId: N:NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch
  href: NDSH.html
  name: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch
  nameWithType: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch
  fullName: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch
  spec.csharp:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Demos
    name: Demos
    href: NDSH.Geospatial.Demos.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap
    name: SearchAndMap
    href: NDSH.Geospatial.Demos.SearchAndMap.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap.Models
    name: Models
    href: NDSH.Geospatial.Demos.SearchAndMap.Models.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap.Models.Services
    name: Services
    href: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch
    name: MetadataSemanticSearch
    href: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch.html
  spec.vb:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Demos
    name: Demos
    href: NDSH.Geospatial.Demos.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap
    name: SearchAndMap
    href: NDSH.Geospatial.Demos.SearchAndMap.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap.Models
    name: Models
    href: NDSH.Geospatial.Demos.SearchAndMap.Models.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap.Models.Services
    name: Services
    href: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.html
  - name: .
  - uid: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch
    name: MetadataSemanticSearch
    href: NDSH.Geospatial.Demos.SearchAndMap.Models.Services.MetadataSemanticSearch.html
