### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
  id: Derived.UnitsOfMeasure
  parent: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema
  children:
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure.MeasureConfiguration
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.ISO19115.Ed2003.DB
references:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure.MeasureConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure.MeasureConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure.MeasureConfiguration.html
  name: MeasureConfiguration
  nameWithType: MeasureConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.ConceptualSchema.Derived.UnitsOfMeasure.MeasureConfiguration
