### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.Metadata.V2003.Application
  commentId: N:NDSH.Geospatial.Metadata.V2003.Application
  id: Application
  parent: NDSH.Geospatial.Metadata.V2003
  children:
  - NDSH.Geospatial.Metadata.V2003.Application.AbstractDS_Aggregate_Type
  - NDSH.Geospatial.Metadata.V2003.Application.DS_Aggregate_PropertyType
  - NDSH.Geospatial.Metadata.V2003.Application.DS_DataSet_PropertyType
  - NDSH.Geospatial.Metadata.V2003.Application.DS_DataSet_Type
  - NDSH.Geospatial.Metadata.V2003.Application.DS_Initiative_PropertyType
  - NDSH.Geospatial.Metadata.V2003.Application.DS_Initiative_Type
  - NDSH.Geospatial.Metadata.V2003.Application.DS_OtherAggregate_PropertyType
  - NDSH.Geospatial.Metadata.V2003.Application.DS_OtherAggregate_Type
  - NDSH.Geospatial.Metadata.V2003.Application.DS_Platform_PropertyType
  - NDSH.Geospatial.Metadata.V2003.Application.DS_Platform_Type
  - NDSH.Geospatial.Metadata.V2003.Application.DS_ProductionSeries_PropertyType
  - NDSH.Geospatial.Metadata.V2003.Application.DS_ProductionSeries_Type
  - NDSH.Geospatial.Metadata.V2003.Application.DS_Sensor_PropertyType
  - NDSH.Geospatial.Metadata.V2003.Application.DS_Sensor_Type
  - NDSH.Geospatial.Metadata.V2003.Application.DS_Series_PropertyType
  - NDSH.Geospatial.Metadata.V2003.Application.DS_Series_Type
  - NDSH.Geospatial.Metadata.V2003.Application.DS_StereoMate_PropertyType
  - NDSH.Geospatial.Metadata.V2003.Application.DS_StereoMate_Type
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.Metadata.V2003.Application
  nameWithType: NDSH.Geospatial.Metadata.V2003.Application
  fullName: NDSH.Geospatial.Metadata.V2003.Application
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.V2003
references:
- uid: NDSH.Geospatial.Metadata.V2003.Application.AbstractDS_Aggregate_Type
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.AbstractDS_Aggregate_Type
  parent: NDSH.Geospatial.Metadata.V2003.Application
  href: NDSH.Geospatial.Metadata.V2003.Application.AbstractDS_Aggregate_Type.html
  name: AbstractDS_Aggregate_Type
  nameWithType: AbstractDS_Aggregate_Type
  fullName: NDSH.Geospatial.Metadata.V2003.Application.AbstractDS_Aggregate_Type
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_Aggregate_PropertyType
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_Aggregate_PropertyType
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_Aggregate_PropertyType.html
  name: DS_Aggregate_PropertyType
  nameWithType: DS_Aggregate_PropertyType
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_Aggregate_PropertyType
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_DataSet_PropertyType
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_DataSet_PropertyType
  parent: NDSH.Geospatial.Metadata.V2003.Application
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_DataSet_PropertyType.html
  name: DS_DataSet_PropertyType
  nameWithType: DS_DataSet_PropertyType
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_DataSet_PropertyType
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_DataSet_Type
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_DataSet_Type
  parent: NDSH.Geospatial.Metadata.V2003.Application
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_DataSet_Type.html
  name: DS_DataSet_Type
  nameWithType: DS_DataSet_Type
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_DataSet_Type
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_Initiative_PropertyType
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_Initiative_PropertyType
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_Initiative_PropertyType.html
  name: DS_Initiative_PropertyType
  nameWithType: DS_Initiative_PropertyType
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_Initiative_PropertyType
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_Initiative_Type
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_Initiative_Type
  parent: NDSH.Geospatial.Metadata.V2003.Application
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_Initiative_Type.html
  name: DS_Initiative_Type
  nameWithType: DS_Initiative_Type
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_Initiative_Type
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_OtherAggregate_PropertyType
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_OtherAggregate_PropertyType
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_OtherAggregate_PropertyType.html
  name: DS_OtherAggregate_PropertyType
  nameWithType: DS_OtherAggregate_PropertyType
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_OtherAggregate_PropertyType
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_OtherAggregate_Type
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_OtherAggregate_Type
  parent: NDSH.Geospatial.Metadata.V2003.Application
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_OtherAggregate_Type.html
  name: DS_OtherAggregate_Type
  nameWithType: DS_OtherAggregate_Type
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_OtherAggregate_Type
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_Platform_PropertyType
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_Platform_PropertyType
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_Platform_PropertyType.html
  name: DS_Platform_PropertyType
  nameWithType: DS_Platform_PropertyType
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_Platform_PropertyType
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_Platform_Type
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_Platform_Type
  parent: NDSH.Geospatial.Metadata.V2003.Application
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_Platform_Type.html
  name: DS_Platform_Type
  nameWithType: DS_Platform_Type
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_Platform_Type
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_ProductionSeries_PropertyType
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_ProductionSeries_PropertyType
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_ProductionSeries_PropertyType.html
  name: DS_ProductionSeries_PropertyType
  nameWithType: DS_ProductionSeries_PropertyType
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_ProductionSeries_PropertyType
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_ProductionSeries_Type
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_ProductionSeries_Type
  parent: NDSH.Geospatial.Metadata.V2003.Application
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_ProductionSeries_Type.html
  name: DS_ProductionSeries_Type
  nameWithType: DS_ProductionSeries_Type
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_ProductionSeries_Type
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_Sensor_PropertyType
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_Sensor_PropertyType
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_Sensor_PropertyType.html
  name: DS_Sensor_PropertyType
  nameWithType: DS_Sensor_PropertyType
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_Sensor_PropertyType
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_Sensor_Type
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_Sensor_Type
  parent: NDSH.Geospatial.Metadata.V2003.Application
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_Sensor_Type.html
  name: DS_Sensor_Type
  nameWithType: DS_Sensor_Type
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_Sensor_Type
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_Series_PropertyType
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_Series_PropertyType
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_Series_PropertyType.html
  name: DS_Series_PropertyType
  nameWithType: DS_Series_PropertyType
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_Series_PropertyType
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_Series_Type
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_Series_Type
  parent: NDSH.Geospatial.Metadata.V2003.Application
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_Series_Type.html
  name: DS_Series_Type
  nameWithType: DS_Series_Type
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_Series_Type
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_StereoMate_PropertyType
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_StereoMate_PropertyType
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_StereoMate_PropertyType.html
  name: DS_StereoMate_PropertyType
  nameWithType: DS_StereoMate_PropertyType
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_StereoMate_PropertyType
- uid: NDSH.Geospatial.Metadata.V2003.Application.DS_StereoMate_Type
  commentId: T:NDSH.Geospatial.Metadata.V2003.Application.DS_StereoMate_Type
  parent: NDSH.Geospatial.Metadata.V2003.Application
  href: NDSH.Geospatial.Metadata.V2003.Application.DS_StereoMate_Type.html
  name: DS_StereoMate_Type
  nameWithType: DS_StereoMate_Type
  fullName: NDSH.Geospatial.Metadata.V2003.Application.DS_StereoMate_Type
- uid: NDSH.Geospatial.Metadata.V2003.Application
  commentId: N:NDSH.Geospatial.Metadata.V2003.Application
  href: NDSH.html
  name: NDSH.Geospatial.Metadata.V2003.Application
  nameWithType: NDSH.Geospatial.Metadata.V2003.Application
  fullName: NDSH.Geospatial.Metadata.V2003.Application
  spec.csharp:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Metadata
    name: Metadata
    href: NDSH.Geospatial.Metadata.html
  - name: .
  - uid: NDSH.Geospatial.Metadata.V2003
    name: V2003
    href: NDSH.Geospatial.Metadata.V2003.html
  - name: .
  - uid: NDSH.Geospatial.Metadata.V2003.Application
    name: Application
    href: NDSH.Geospatial.Metadata.V2003.Application.html
  spec.vb:
  - uid: NDSH
    name: NDSH
    href: NDSH.html
  - name: .
  - uid: NDSH.Geospatial
    name: Geospatial
    href: NDSH.Geospatial.html
  - name: .
  - uid: NDSH.Geospatial.Metadata
    name: Metadata
    href: NDSH.Geospatial.Metadata.html
  - name: .
  - uid: NDSH.Geospatial.Metadata.V2003
    name: V2003
    href: NDSH.Geospatial.Metadata.V2003.html
  - name: .
  - uid: NDSH.Geospatial.Metadata.V2003.Application
    name: Application
    href: NDSH.Geospatial.Metadata.V2003.Application.html
