### YamlMime:ManagedReference
items:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation
  commentId: N:NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation
  id: Citation
  parent: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common
  children:
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiAddressConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiCitationConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiContactConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiDateConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiOnlineResourceConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiResponsiblePartyConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiSeriesConfiguration
  - NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiTelephoneConfiguration
  langs:
  - csharp
  - vb
  name: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation
  nameWithType: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation
  type: Namespace
  assemblies:
  - NDSH.Geospatial.Metadata.ISO19115.Ed2003.DB
references:
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiAddressConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiAddressConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiAddressConfiguration.html
  name: CiAddressConfiguration
  nameWithType: CiAddressConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiAddressConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiCitationConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiCitationConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiCitationConfiguration.html
  name: CiCitationConfiguration
  nameWithType: CiCitationConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiCitationConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiContactConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiContactConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiContactConfiguration.html
  name: CiContactConfiguration
  nameWithType: CiContactConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiContactConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiDateConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiDateConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiDateConfiguration.html
  name: CiDateConfiguration
  nameWithType: CiDateConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiDateConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiOnlineResourceConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiOnlineResourceConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiOnlineResourceConfiguration.html
  name: CiOnlineResourceConfiguration
  nameWithType: CiOnlineResourceConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiOnlineResourceConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiResponsiblePartyConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiResponsiblePartyConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiResponsiblePartyConfiguration.html
  name: CiResponsiblePartyConfiguration
  nameWithType: CiResponsiblePartyConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiResponsiblePartyConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiSeriesConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiSeriesConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiSeriesConfiguration.html
  name: CiSeriesConfiguration
  nameWithType: CiSeriesConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiSeriesConfiguration
- uid: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiTelephoneConfiguration
  commentId: T:NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiTelephoneConfiguration
  href: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiTelephoneConfiguration.html
  name: CiTelephoneConfiguration
  nameWithType: CiTelephoneConfiguration
  fullName: NDSH.Geospatial.MetadataDB.Relational.Configurations.Common.Citation.CiTelephoneConfiguration
