name: Deploy Documentation to GitHub Pages

on:
  workflow_run:
    workflows:
      - "Build Documentation"
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docfx-site
          path: Help/doc/api

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Help/doc/api
