name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  build_metadata:
    name: Build Metadata YMLs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build docfx metadata
        uses: nunit/docfx-action@v2.4.0
        with:
          args: "metadata Help/doc_source/docfx.json"

      - name: Build docfx html
        uses: nunit/docfx-action @v2.4.0
        with:
          args: "build Help/doc_source/docfx.json"
