name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  build_metadata:
    name: Build Metadata YMLs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build docfx html
        uses: nunit/docfx-action @v4.0.0
        with:
          args: "Help/doc_source/docfx.json"
